// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgxDoItWXqrgGHyoDp8jJHmpYVuBYis8k',
    appId: '1:1079510164274:web:61cc368ccfb4ee4773ed2b',
    messagingSenderId: '1079510164274',
    projectId: 'foodtrack-61f69',
    authDomain: 'foodtrack-61f69.firebaseapp.com',
    storageBucket: 'foodtrack-61f69.firebasestorage.app',
    measurementId: 'G-RPBH91VJ84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXPtoWNog1YXQ_rkwHks6FeftuaRVLMA0',
    appId: '1:1079510164274:android:88c30a54be07eb4573ed2b',
    messagingSenderId: '1079510164274',
    projectId: 'foodtrack-61f69',
    storageBucket: 'foodtrack-61f69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpUauC3ec5XQHQTQMJzqiDZQCQcl4kgw',
    appId: '1:1079510164274:ios:32f7bf0eb90e042a73ed2b',
    messagingSenderId: '1079510164274',
    projectId: 'foodtrack-61f69',
    storageBucket: 'foodtrack-61f69.firebasestorage.app',
    iosBundleId: 'com.example.foodtrack',
  );
}
